version: '3.4'
services:
  app:
    build:
      context: ./snadm
      dockerfile: ./Dockerfile.dev
    depends_on:
      - database
      - redis
    ports: 
      - "3000:3000"
    volumes:
      - ./snadm:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: ./snadm/env/.app
    command: "bundle exec rails s -b 0.0.0.0"
    environment:
      RAILS_ENV: development
  database:
    image: postgres:12.1
    volumes:
      - ./:/app/
      - db_data:/var/lib/postgresql/data
    env_file: ./snadm/env/.postgres
      #  pgcli:
      #    image: morzzz007/pgcli
      #    stdin_open: true
      #    env_file: ./snadm/env/.pgcli
      #    depends_on:
      #      - database
  redis:
    image: redis:5.0.7
  swagger_editor:
    image: swaggerapi/swagger-editor
    environment:
      SWAGGER_FILE: /swagger.yml
    volumes:
      - ./swagger/api-documentation.yml:/swagger.yml
    ports:
      - "7777:8080"
volumes:
  gem_cache:
  db_data:
  node_modules:
  backups:
