version: '3.4'

services:
  app:
    build:
      context: ./snadm
      dockerfile: Dockerfile.dev
    depends_on:
      - database
      - redis
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: ./snadm/env/.app
    environment:
      RAILS_ENV: development
  database:
    image: postgres:12.1
    volumes:
      - ./:/app/
      - db_data:/var/lib/postgresql/data
    env_file: ./snadm/env/.postgres
      #  pgcli:
      #    image: morzzz007/pgcli
      #    stdin_open: true
      #    env_file: ./snadm/env/.pgcli
      #    depends_on:
      #      - database
  redis:
    image: redis:5.0.7
      #  sidekiq:
      #    build:
      #      context: .
      #      dockerfile: Dockerfile
      #    depends_on:
      #      - app      
      #      - database
      #      - redis
      #    volumes:
      #      - .:/app
      #      - gem_cache:/usr/local/bundle/gems
      #      - node_modules:/app/node_modules
      #    env_file: .env
      #    environment:
      #      RAILS_ENV: development
      #    entrypoint: ./entrypoints/sidekiq-entrypoint.sh
  swagger_ui:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /swagger.yml
    volumes:
      - ./swagger/api-documentation.yml:/swagger.yml
    ports:
      - "7979:8080"
volumes:
  gem_cache:
  db_data:
  node_modules:
  backups:
