openapi: 3.0.0
info:
  version: 0.0.1
  title: Api actes Etat Civil
paths:
  '/api/v1/sessions':
    post:
      summary: 'Nouvelle session'
      tags:
        - Agents
      description: 'Crée une nouvelle session pour un agent'
      responses:
        201:
          description: Session crée avec succès
    get:
      summary: "Recherche un acte d'état civil"
      tags:
        - Actes d'état civil
      responses:
        200:
          description: Résultats de la recherche
        401:
          description: Non autorisé
        422:
          description: Paramètres invalides
        500:
          description: Erreur      

  '/api/v1/actes':
    post:
      summary: "Nouvel acte d'état civil"
      tags:
        - Actes d'état civil
      responses:
        201:
          description: Acte crée avec succès
        401:
          description: Non autorisé
        422:
          description: Paramètres invalides
        500:
          description: Erreur 
          
  '/api/v1/actes/{id}':          
    get:
      summary: "Affichage d'un acte de naissance"
      tags:
        - Actes d'état civil
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200: 
          description: ''
        401:
          description: Non autorisé
        422:
          description: Paramètres invalides
        500:
          description: Erreur  
          
  '/api/v1/actes/{id}/delivrer':          
    get:
      summary: "Impression d'un acte de naissance"
      tags:
        - Actes d'état civil
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200: 
          description: ''
        401:
          description: Non autorisé
        422:
          description: Paramètres invalides
        500:
          description: Erreur       

