source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'
gem 'rails', '~> 6.1.0.rc2'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'bcrypt', '~> 3.1'
gem 'rack-cors', '~> 1.1'
gem 'jwt', '~> 2.2'
gem 'lograge', '~> 0.11.2'
# => https://github.com/nebulab/simple_command
gem 'simple_command'

group :development, :test do
  gem 'byebug', '~> 11.1', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 4.0'
  gem 'factory_bot_rails', '~> 6.1'
end

group :development do
  # => https://github.com/rubysec/bundler-audit
  gem 'bundler-audit'
  gem 'guard-rspec'
  # => https://github.com/teeparham/gemdiff
  gem 'gemdiff'
  gem 'annotate'
  gem 'listen', '~> 3.2'
  gem 'rubocop-rails', '~> 2.8', require: false
  # => https://github.com/pawurb/ruby-pg-extras
  gem 'ruby-pg-extras', '~> 1.2'
  # => https://github.com/bobf/strong_versions
  gem 'strong_versions', '~> 0.4.5'
end

group :test do
  # https://github.com/simplecov-ruby/simplecov
  gem 'simplecov', require: false
end
